Pipelines: 
    Model Layer:
        - # LIGHTGBM REGRESSOR MODEL
            name: lightgbm
            source: Estimator
            pickle_path: lgbm.pkl
            model: 
                class: LGBMRegressor
                params: {
                    'n_estimators': 20000, 
                    'learning_rate': 0.01,
                    'boosting_type': 'gbdt', 
                    'colsample_bytree': 0.80,        
                    'min_child_weight': 40.0,
                    'num_leaves': 16, 
                    'objective': 'regression', 
                    'subsample': 0.50, 
                    'subsample_freq': 5,
                    'metric': 'custom'
                } # default params, will be overwritten if hpt is used
            params: # Estimator params, excluding model
                early_stopping_rounds: 50
                random_state: 100 
                variance_penalty: 1
                verbose: 500
                eval_metric: 'mae'
                validation_scheme: "train_test_split"
                n_splits: 3
            hpt: 
                name: HyperOptModelSelection
                params:    
                    max_evals: 5 # number of hyperopt iterations to run
                    space: lgbm_space
                    is_maximize: False # optimization flag, True -> Maximize, False -> Minimize
                        
        - # XGBOOST Regresssor Model
            name: xgboost
            source: Estimator
            pickle_path: xgb.pkl # path to save fitted model
            model: 
                class: XGBRegressor
                params: {
                    'learning_rate':0.01, 
                    'n_estimators':20000,
                    'metric': 'custom'
                } # default params, will be overwritten if hpt is used
            params: # Estimator params, excluding model 
                early_stopping_rounds: 100
                random_state: 100 
                variance_penalty: 1
                verbose: 500
                eval_metric: 'mae'
                validation_scheme: "TimeSeriesSplit"
                n_splits: 3
            hpt: 
                name: HyperOptModelSelection
                params:    
                    max_evals: 5 # number of hyperopt iterations to run
                    space: xgb_space
                    is_maximize: False # optimization flag, True -> Maximize, False -> Minimize
